spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://localhost:5432/music_recommends
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-stacktrace: never
logging:
  level:
    root: info
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_1
  swagger-ui:
    path: /index.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    version: 1.0.0